apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: openshift-gitops

spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: resources
    repoURL: 'https://github.com/Everything-is-Code/openshift-pipelines.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true